### ISSUE TITLE
mat64: add Tranpose type

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#123]
In #121 [I proposed a new type Transpose](https://github.com/gonum/matrix/issues/121#issuecomment-94210532).

I suggest we add a `Transpose struct { Matrix }` with a Dims and At method that transposes the embedded matrix. In itself, this is not wildly useful, but it can be used internally to signal the transpose state to the Mul routine. This allows us to retire the MulTrans API, keeping its optimisations (we could keep it, but this is worth thinking about).

Identifying the transpose state would be done by a helper that walks the T chain until the underlying Dense (or other optimisable type) is found, keeping track of the state. Additionally, I think a helper T(Matrix) Matrix would be worthwhile to optimise this process:

```
func T(m Matrix) Matrix {
    if t, ok := m.(Transpose); ok {
        return t.Matrix
    }
    return Transpose{m}
}
```

**Comment by btracey** [comment]
Reply is on the long side, just to set the stage of my argument.

This type seeks to solve a real problem. We have to deal with the fact that transpose is a common operation, and for many matrix methods the transpose can be dealt with implicitly instead of allocating and copying the transposed matrix. Our present solution to the problem makes an unnecessarily large API surface, and we can probably do better. 

In my opinion, any effective solution must:
1) Be easy and legible in the context of matrix operations
2) Be the same mechanism with all the matrix types
3) Cause minimal interference 

I'm worried about the complications in state that come from this. Take, for example,
````
a := mat64.NewDense(2,3, []float64{1,2,3,4,5,6})
aTrans := mat64.Transpose{a}
aTrans.Set(0, 1, 16)
````
This sets the {0,1} entry, which is definitely confusing to a reader (sure, it's terrible code, but we still need to think about what we enable). 

My counterproposal is to make the type solely for communicating the matrix should be transposed for the operation, and worthless otherwise. I would propose that the type be ````type T struct{Matrix}````. This would allow, for example, ````m.Mul(mat64.T{a}, mat64.T{b})````. I think this is more legible than ````m.Mul(mat64.Transpose{a}, mat64.Transpose{b})````, and since it's fewer characters it encourages use within the expression. 

Secondly, I would suggest that T does NOT have any overloaded methods, and instead includes some documentation saying as much and that its only purpose is to communicate the transposedness of the function argument. Yes, if someone does 
````
aTrans := mat64.T{a}
aTrans.At(0,1)
````
they will be surprised by the result, but I think transpose not affecting any of the methods is much simpler than transpose only affecting At and Dims.

**Comment by kortschak** [comment]
>I'm worried about the complications in state that come from this. Take, for example,

```
a := mat64.NewDense(2,3, []float64{1,2,3,4,5,6})
aTrans := mat64.Transpose{a}
aTrans.Set(0, 1, 16)
```

This is not legal; `aTrans` is a `Matrix`, not a `Mutable`.

>My counterproposal is to make the type solely for communicating the matrix should be transposed for the operation, and worthless otherwise. I would propose that the type be type T struct{Matrix}. This would allow, for example, `m.Mul(mat64.T{a}, mat64.T{b})`. I think this is more legible than `m.Mul(mat64.Transpose{a}, mat64.Transpose{b})`, and since it's fewer characters it encourages use within the expression. 

What does `mat64.T{mat64.T{a}}` mean here?

Here is my proposal fully fleshed (except caveat below - which makes me more inclined towards yours; with yours the meaning of T needs to be very clearly explained).

```
// Transpose wraps a Matrix to indicate the wrapped matrix is transposed.
type Transpose struct {
	Matrix
}

// T returns the Transpose wrapped transpose of m or unwraps a Transpose wrapped transpose.
func T(m Matrix) Matrix {
	if t, ok := m.(Transpose); ok {
		return t
	}
	return transpose{m}
}

// Dims returns the number of rows and columns in the matrix.
func (m Transpose) Dims() (r, c int) {
	r, c = m.Matrix.Dims()
	return c, r
}

// At returns the element at row r, column c.
func (m Transpose) At(r, c int) float64 { return m.Matrix.At(c, r) }
```

The situation is not quite so simple though. Adding this means we need to go through all the paired parameter methods (not just `Mul`) and make sure they are Transpose aware. We also need the pointer walker for bad cases - this is actually potentially subtle, or at least marked with a reasonable warning:

```
// isTransposedRawMatrixer returns whether the the matrix should be interpreted
// as transposed by the Transpose wrapper mechanism.
func isTransposed(m Matrix) bool {
	t, transposed := m.(Transpose)
	for {
		var ok bool
		t, ok = t.(Transpose)
		if !ok {
			return transposed
		}
		transposed = !transposed
	}
}
```

**Comment by kortschak** [comment]
Additional question: How is `m.Add(mat64.T{a}, b)` interpretted?

**Comment by kortschak** [comment]
I've had more of a think about this, and I think a Transpose with At and Dims defined is the correct approach.

The reason for this is that if we had a mat64 package with no optimisations (we don't but bear with me), the method replacement approach would just work. With optimisations we need to add code to the RawMatrixer/Vectorer/etc paths. 

However, with the strictly annotating approach, we need to add code not just to those paths, but also to the pure Matrix implementations.

As an additional benefit, we get TCopy for free and can drop that interface and method (it can be expressed as `m.Copy(mat64.T(a))` - possibly with optimisations for common cases).

The only concern I have is that if another type wraps a wrap-transposed matrix, the tests for transposition fail. This is not horrendous though, since what we get then is just the slow path. We should note though in the docs that a T() call should be used last if wrapping a matrix (preferably at a matrix operation call as your approach suggests).

Another thing to consider is that Transpose could be made unexported under this scheme without  any problem AFAICS, and which would reduce the complexity of transpose testing code down to a single type assertion since client would not be able to repeatedly wrap matrices (except by interleaving other wrappers - when we get the slow path being executed because the unwrapped matrix will not be a RawMatrixer/Vectorer/... anyway).

**Comment by btracey** [comment]
I agree with your points. I also had temporarily forgotten that just the Matrix methods would be available. 

However, this raises a different issue, which is while Transpose satisfies Matrix, it does not satisfy Triangular. We would need to have at least a second Transpose function. I wonder if there's any clean way around it.  

What's the benefit to the function as opposed to just having ````type mat64.T struct````? We can document that we will only test for wrapping once, and more than once would lead to the slow path.

**Comment by kortschak** [comment]
>I wonder if there's any clean way around it. 

I can't think of one. An alternative is to add a T method and return the appropriately wrapped type, I don't see that it's a win, but it equally not worse.

>We can document that we will only test for wrapping once, and more than once would lead to the slow path.

I prefer taking things out of people's hand if at all possible. With the func approach Transpose can be unexported (we would then export IsTransposed).

**Comment by btracey** [comment]
Actually, the T method would be a win, wouldn't it?
````
// sd is a *SymDense
dense.Mul(dense, sd.T())
symDense.Mul(sd.T(), sd)
````
The methods would be
````
func (*Dense) T() denseTranspose  // implements Matrix
func (*SymDense) T() symmetricTranspose // implements Symmetric
````
As you suggested, the types aren't exported, so we don't need to worry about nesting. Furthermore, we can have an unexported "transposer" interface where we can test if any of the specific transposed types are present. The only issue is that we need a way for a generic "Matrix" to be transposed, which probably mandates an exported type.

**Comment by kortschak** [comment]
The methods would return Matrix (I really don't like APIs that refer to unexported types in the godoc).

There would be a func T(Matrix) Matrix for the general case (unfortunately this still has the possibility of nesting, because it could take a T'd Dense or TriDense (did you mean to refer to SymDense - we can add a T to that as well - { return m }.

We can add to unexported interface if we see that it is necessary,

**Comment by kortschak** [comment]
So here is the model now:

```

// transposeDense wraps a Dense to give a no-copy transpose.
type transposeDense struct {
	Dense *Dense
}

// T returns the transpose of m. Changes to m are reflected in the transpose.
func (m *Dense) T() Matrix { return transposeDense{m} }

func (m transposeDense) T() Matrix { return m.Dense }

func (m transposeDense) Dims() (r, c int) {
	r, c = m.Dense.Dims()
	return c, r
}

func (m transposeDense) At(r, c int) float64 { return m.Dense.At(c, r) }
```

We don't need to add a general purpose T function or type since this is a optimisation matter. Clients can do what they want with their matrix types.

I particularly like the SymDense version:

```
// T returns the transpose of s. Changes to s are reflected in the transpose.
func (s *SymDense) T() Matrix { return s }
```

**Comment by btracey** [comment]
The problem is that this doesn't work with, e.g. Triangular because Matrix doesn't implement Triangular. I guess we need to do what we've done in other places with, i.e.
````
// TTri returns the transpose of a Triangular matrix.
func TTri() Triangular{
}
````
maybe? This is where issue 6264 would be really nice.

**Comment by kortschak** [comment]
What is 6264?

**Comment by btracey** [comment]
Go issue 6264. Reguest to change interface satisfaction based on assignability rather than explicit type.

**Comment by kortschak** [comment]
Do we have any further thoughts on this?

**Comment by btracey** [comment]
Sorry for the long delay.

I agree with the need. I agree with the basic ideas. I don't think the single Transpose type works how we want. We need to be able to say TriDense.T() and have it work wherever. I also think we need to export everything needed so that others can look for transposes if they need to. This encourages building an ecosystem of matrix math if the need arises. 

We also want to make switching over matrix types to be easy. 

Here is the start of a suggestion:

1) For each major interface type, there is a corresponding transpose type. Matrix --> Transpose, Symmetric --> TransposeSym, etc.
2) The Transpose types have the interface as a field
````
type Transpose struct {
      Matrix Matrix
}

type TransposeTri struct {
    Triangular Triangular
}
````
3) Each of the Transpose types implements the necessary interfaces. Transpose implements Matrix, TransposeTri implements Triangular
4) The Transpose types have exactly one additional function, which is to implement the "Untransposer" interface
````
// Untranspose returns the untransposed matrix from a Transpose type
type Untransposer interface {
   Untranspose() Matrix
}

func (t TransposeTri) Untranspose() Matrix {
      return t.Triangular
}
````
5) Each of the concrete types has a T-style methods to return the transpose type
````
func (m *Dense) T() Matrix {
     return Transpose{m}
}

func (t *TriDense) TTri() Triangular {
    return TransposeTri{t}
}
````

Here is the last suggestion that I think would make this work really well, if we're willing to accept the cost. We add the transpose methods to the interface definitions. So, we would have
````
type Matrix interface {
     At(i,j int) float64
     Dims() (int,int)
     T() Matrix
}
````
This is very easy for any implementer of Matrix to meet, as they just need to put their matrix inside the Transpose type. The various transpose types also add these methods
````
func (t TransposeTri) T() Matrix {
    return t.Triangular
}

func (t TransposeTri) TTri() Triangular {
    return t.Triangular
}
````

--------
So what does this do? First of all, it allows easy transposing of all matrix types. If you need a Matrix transposed, you use T(). If you need a Triangular transposed, you use TTri(). Second of all, it allows implementers on top of matrix to be able to use transposes without needing to know the specific type
````
// MyFun computes c = a^T * b * b^T.
func MyFun(a Matrix, b Symmetric) Matrix {
    var s mat64.Symmetric
    s.MulSym(b, b.TSym()) // we'll have this eventually
    var c mat64.Dense
    c.Mul(a.T(), s.T())
}
````
This function works no matter what. A could be a Dense matrix, or it could be a symmetric banded matrix. The types aren't lost, so Mul can still switch over the right type. The caller of MyFun could have given in the various Transpose types and it'll still work. 

Because of the Untransposer interface, it also allows us to easily switch over the cases
````
// isTransposed returns whether the matrix is wrapped in a tranposed type. If it is, it returns the 
// untransposed matrix, otherwise it returns the original matrix.
func isTransposed(a Matrix) (Matrix, bool){
    ut, ok := a.(Untransposer)
    if !ok {
        return a, false
    }
    return ut.Untranspose(), true
}
````
Again, this works for the whole matrix heirarchy (and can then be type switched to find the special cases). 

The Transpose types are exported, so it's possible to  construct russian dolls of them. First of all, I don't see any reason why a user would do so. The only time a Transpose should ever be constructed explicitly is in the method implementations. Otherwise users can just use T() (etc.). Secondly, if someone wants to be mean and nest them, all of the algorithms work fine, they'll just lose the ability to special case.

**Comment by kortschak** [comment]
This seems to be pretty much https://github.com/gonum/matrix/issues/123#issuecomment-94413830 with exported Transpose and adding T to Matrix. Is that a fair assessment?

(The intention was always to remove MulTrans and have that functionality performed based on transpose state).

**Comment by btracey** [comment]
Also Transpose contains Matrix and not Dense.

(I agree that was the intention, just reiterating why I think it should be a part of the Matrix interface)

**Comment by kortschak** [comment]
Sure. Then SGTM. Do you want to do this?

**Comment by btracey** [comment]
If you'd like I can. It'll have to wait a few hours before I can do so at least, so if you'd like to do it that's fine with me as well.

**Comment by kortschak** [comment]
I'll leave it for you.

**Comment by btracey** [comment]
This has been done.
