### ISSUE TITLE
Surprising replacement of matrix data

### ISSUE THREAD

**Issue by btracey** [gonum/matrix#130]
In the following code:

````
base := make([]float64, n*n)
for i := range base {
	base[i] = rand.Float64()
}
b := NewDense(n, n, base)
b.MulTrans(bm, true, bm, false)
````
The changes to b are not reflected in base. This is surprising. New data needs to be allocated in the interim to avoid races, but the final result should probably be copied into the data rather than being replaced with a new slice.

**Comment by kortschak** [comment]
s/bm/b/g?

**Comment by btracey** [comment]
Yes, sorry, it should be 
````
b.MulTrans(b, true, b, false)
````

**Comment by kortschak** [comment]
Mul works this way too. I think we just document that a<-mulOp(a) does not result in data being stored in the original slice.

**Comment by kortschak** [comment]
How do you propose we deal with this? In the case that the matrix is square we can do what you do in RankOne; copy back onto the receiver. Otherwise we just panic because shape - does that sound fair?

**Comment by kortschak** [comment]
This is interesting. In looking into it, there is a bug in the dimensional safety we should have for Mul. For example, the test for inner should not be able to say this:

```
mWant.Mul(mWant, y)
mWant.Mul(x, mWant)
```

Since mWant is not the same dims as mWant . y or x . mWant. Yet it passes.

This occurs because we have in the case where `m == a || m == b` a call to `w.reuseAs(ar, bc)` that is independent of m. This should not happen. There is a similar bug in TestSVD:

```
svd.U.Mul(svd.U, s)
svd.U.Mul(svd.U, vt)
```
