### ISSUE TITLE
matrix: propose add cmat128 package

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#134]
At this stage it would be a stripped down complex128 version of the mat64 interface definitions (probably just the basic arithmetic operations - maybe with their implementations via cgo in the first instance) and a Dense representation. With a view to add those operations in the future and significantly to allow us to have an available representation for results from some of the lapack routines that generate complex results on some inputs.

**Comment by btracey** [comment]
I think we are in a stable enough state that this is a good idea. I'm pretty happy with our general decisions (the receiver is modified, if something is modified, it is a receiver, if not it's a function) and type interactions. The remaining concerns I have are with the higher-level functions (Solve and Eigen, for example), which will be aided by cmat128. 

As a side note, I spent a bit of time looking into go implementations of Eigen for symmetric matrices (Dsyevr, I believe) in an attempt to help the redesign along, but there are a lot of steps to get there.

**Comment by kortschak** [comment]
That was the provocation. I may put together something that touches this over the weekend. It would be cmat128.Matrix, and the basic arithmetic operations (mainly due to lack of testing more than anything else).

In a semi related direction, I have been thinking of retiring some of our interfaces - they have served well as a design document, but we don't use many of them and they are probably no longer necessary. Though I am not firmly wedded to this line of thinking.

**Comment by btracey** [comment]
Do we have any sense how much could be autogenerated? It would be great if
cmat64 could mostly appear from mat64 (with some help I'm site). My minimal
experience trying to use the ast package suggests at the very least I would
need examples to copy in order to help that effort.

I agree with retiring the interfaces. In my opinion, if there's a specific
interface that we know is useful, it's good to have so there's a
"canonical" location. Otherwise, we'll just make sure our signatures are
interfacable  (as we do now). For example,  stat/dist may add some
interfaces even though it doesn't use then internally, as they would be
used by a sampling package for instance

**Comment by kortschak** [comment]
My plan was to split files in mat64 into *_common.go and *_real.go where methods and functions are not already in their own files, then generate from the *_common.go and already generic files.

I'll file an issue for an interface retirement plan - I guess it would be a 404(k) - sorry.

**Comment by kortschak** [comment]
I've just had a bit of a play with this and I think the ideas @jonlawlor put forward in https://github.com/gonum/matrix/issues/79#issuecomment-69828645 make sense (I was using CmplxAt), but we run into cyclic dependency issues.

If we mirrror mat64.Matrix, then a cmat128.Matrix cannot also satisfy mat64.Matrix because T collides. The alternative is to have `cmat128.Matrix interface { mat64.Matrix; CmplxAt(r, c int) complex128 }`, but this has issues with how Eigen gains access to the complex matrix type to return - one possibility is to require that the client assert to cmat128.Matrix and convert to cmat128.Dense. This seems kind of horrible.

It sort of feels like the world is pushing towards the notion that mat64 and cmat128 are inseparable. This is probably less horrible than what we might end up with other ways.

**Comment by btracey** [comment]
The tradeoff is naming vs. odd interchanges. The two types do not overlap very much. For Dense matrices, eigenvalues/vectors are the only example where the two overlap in our current package, and even that does not occur for symmetric matrices or triangular matrices. 

As far as I see it, a complex-backed matrix should not satisfy mat64.Matrix. complex128(1) + float64(1)  is a compile error in Go, so why shouldn't mat64.Add(mat64.Matrix, cmat128.Matrix) also be a compile error (at least as far as gonum types are concerned)? 

There are two questions. 1) Should there be one package or two 2) If one is "two", then which should import which. It seems to me (and I could be convinced), that it should be two packages. The tradeoff appears to be making the signature of Eigen weird, or making the names of all of the complex operations weird. The rule right now is to make functions with different behaviors have different names. This is a fine rule, but it implies we end up with AtCmplx, SumCmplx, SumSymCmplex, etc. etc. when the packages are combined. Assuming the packages are split, we get to keep all of the same naming (but now with a different package name). 

As far as I know, the one issue is the design of Eigen for Dense matrices. The eigenvalues (and I think Eigenvectors) for SymDense and TriDense are all real, so the problem is only limited to Dense. Eigenvalues are easy, because they can return []complex128, which does not cause cyclical imports. Thus, it seems like the the cyclical import issue comes down to eigenvectors of Dense matrices. It seems like that's a small edge case to trade in order to have all of the complex methods have good names. 

It does beg the question of writing methods that are agnostic with respect to complex or real matrices. Unfortunately, I think that's the cost of Go -- a function is either float64 or complex128, not both.

**Comment by kortschak** [comment]
Thanks.

That all makes sense and I'm happy with that. The last point is easily addressable at the point of the client's call by either them or use providing a shim if they want to hand the other type to a function.

**Comment by kortschak** [comment]
One thing that remains difficult is a non-integer Pow. One possible solution is that non-integer Pow is only a method on cmat128.Dense.

**Comment by btracey** [comment]
Yes. Another possibility is that mat64 imports cmat128. I don't know how many methods construct real matrices from complex ones.

**Comment by kortschak** [comment]
I don't like the idea of having mat64 importing cmat128 (or vice versa) - doing that really suggests they should be one package. Having cmat128.Dense.PowR only makes sense, because it shows that the result may be complex. If the result ends up having no imaginary part, then it can be copied to a mat64.Dense - we can provide a pair of shims in the matrix root package (or just leave that to clients).

e.g.

```
// Real is the real part of a complex matrix.
type Real struct {
    Matrix cmat128.Matrix
}

func (m Real) Dims() (r, c int)    { return m.Matrix.Dims() }
func (m Real) At(r, c int) float64 { return real(m.Matrix.At(r, c) }
func (m Real) T() mat64.Matrix     { return Real{m.Matrix.T()} }
```

**Comment by btracey** [comment]
This has been surpassed by combining the packages.
