### ISSUE TITLE
mat64: delete *Dense L and U methods and associated interfaces

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#186]
These can be achieved via a t.Copy(m) where t is a *TriDense if we add Copy to *TriDense. This simplifies the API and makes a more efficient path for many things a natural consequence of the operation.

**Comment by btracey** [comment]
The signature needs to be different than copy (per our non-overlapping rules). Copy copies the entire matrix, while this would copy only half a matrix. Presumably CopyTri would only copy from other triangular matrices, to match CopySym. 

I would vote we steal an earlier idea and use LFrom and RFrom to extract the upper and lower from an arbitrary matrix. This has the added effect (a feature in my mind) that it would always get the whole min(m,n) x min(m,n) part, rather than Copy, which implies only taking enough to fill the receiver or argument (no size check).

**Comment by kortschak** [comment]
>Copy copies the entire matrix, while this would copy only half a matrix.

That's not true. Copy copies the elements at the intersection of the two values - just as the copy built-in does. In this case that would be the triangle when the dims match or the source is larger.

>I would vote we steal an earlier idea and use LFrom and RFrom to extract the upper and lower from an arbitrary matrix. This has the added effect (a feature in my mind) that it would always get the whole min(m,n) x min(m,n) part

This can be achieved by extending the semantics of Clone by adding a clause that the clone operation obeys the semantics of the receiver. Part of the drive here is to reduce the number of elements we are dealing with and LFrom/RFrom are pretty much just a renamed L and U.

One question that this raises though is in a non-square matrix, when a triangle is taken from the longer axis, where is it extracted from.

There is one thing that I would add though, and that is a ResetTri(upper bool) to TriDense which also calls Reset.

**Comment by btracey** [comment]
>> Copy copies the entire matrix, while this would copy only half a matrix.
> That's not true. Copy copies the elements at the intersection of the two values - just as the copy built-in does. In this case that would be the triangle when the dims match or the source is larger.

I see. That's a good way of looking at it. It still justifies having CopySym and not Copy on SymDense, because the "footprint" of *SymDense is larger than the degrees of freedom.

I don't think we should overload Clone though. The difference between "Make a new one of this matrix" and "Make a subset of this matrix" is significant. It does work very nicely with Copy.

> One question that this raises though is in a non-square matrix, when a triangle is taken from the longer axis, where is it extracted from.

It has to be from 0,0. This is how copy behaves. It starts at 0,0 and starts filling. If you want a different subset use a View.

> There is one thing that I would add though, and that is a ResetTri(upper bool) to TriDense which also calls Reset.
Why include upper? Zero size = flexible. If the TriDense is size zero, the uplo is ignored as well.

**Comment by kortschak** [comment]
CopySym needs to exist, yes. This is a proposal for triangular matrices.

>It has to be from 0,0. This is how copy behaves. It starts at 0,0 and starts filling. If you want a different subset use a View.

Good.

>Why include upper? Zero size = flexible. If the TriDense is size zero, the uplo is ignored as well. 

This is not how Copy works. The dims of the receiver are unaltered. If you have a zero TriDense, and you call Copy, you have a zero TriDense.

However, yes there is a flaw in my approach.

The issue is that if you have a TriDense that you could use, but the triangle is wrong, there is currently no way to get it to be the other triangle. Maybe just add a method SetTriangle(upper bool) which does nothing but set the triangle - leaving the data that is there already untouched.

**Comment by btracey** [comment]
As you say, copy doesn't change the size. If the TriDense is zero then in doesn't matter if it is upper or lower, nothing happens. For all other operations, there is a "correct" receiver size, and in the case of TriDense, a correct uplo. If the TriDense is zero, then all of that is adjusted automatically. So you can call TriDense.Reset() (when it exists) to reuse the data in your matrix. There is then one edge case, where you have a TriDense and you want to copy a specific triangular half. This could be a good use for L/R/CloneL/CloneR, and here the input m must be square. As far as I can tell this is only a problem for Copy, and so adding two special functions to handle this case is better then a SetTrianguar which has a ton of potential for incorrect use.

**Comment by kortschak** [comment]
I'm confused about things happening automatically in the situations I'm aiming at; nothing gets changed by Copy except the data. I think we are talking at crossed purposes here.

I agree that SetTriangular is open to abuse, but the absence of a similar mechanism means that if you have a triangular temporary workspace for one uplo, you cannot use it for the other without gitting the blas64.Triangular. Reset does not work in the case where Copy is the mechanism for getting the data across. Maybe this isn't a problem.

**Comment by btracey** [comment]
We must be talking at crossed purposes. Let's say a and b are upper triangular mxm matrices, and c and d are lower triangular matrices. The following should be made to work fine
````
var tmp TriDense
tmp.Add(a,b)
// Use tmp
tmp.Reset()
tmp.Add(c,d)
````
A zero-sized matrix in mat64 has no information. Therefore, Reset effectively zeros out both the size and orientation of the triangular. Thus, in the second add, Tmp 'inherits' both the  nxn size and the lower orientation.  As far as I can see, Copy is the only function for which you would need to set the uplo explicitly. All other functions you can just call Reset() before using the function.

**Comment by kortschak** [comment]
Yes, this proposal only discusses a mechanism to mimic the current L and U methods while reducing the API surface.

(What do you expect the behaviour to be from the example above though? I don't really see how what I'm saying impacts on that at all).

The options as I see it are:

1. Don't allow changes via the mat64 API but add Copy to TriDense - this is the simplest and probably what we should go with since the change can be made via blas.Triangular and it's really only an efficiency thing.
2. Make CopyL and CopyU which do a copy and set the uplo at the same time (I don't like this).
3. Allow changes to the TriDense's uplo via the mat64 API (`SetTriangle(upper bool)`) and add Copy to TriDense.

**Comment by btracey** [comment]
Okay. I thought we disagreed on the scope of the problem.

We should add copy to TriDense.

Instead of SetTriangle, I would vote for a "ResizeTri(n, upper bool)".  In my opinion, this makes it much more clear that the old triangle is effectively gone. ResizeTri should probably zero out data in the new half just to make sure there aren't any residuals.

What I want to avoid is the case where people are being clever and trying to store two different matrices in the same slice, and then using SetTriangle to switch back and forth. If you want to do that, you should be using the blas64 types.

**Comment by kortschak** [comment]
Agreed. I think in the first instance we don't add anything and add something like ResizeTri if there is a reasonable motivation for it internally or someone makes a good argument for it externally.

**Comment by btracey** [comment]
SGTM.
