### ISSUE TITLE
coveralls: last build was in june

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#238]
The last coveralls build was in early June https://coveralls.io/builds/2756286. Do we have any idea why this is not being done?

/cc @jonlawlor

**Comment by jonlawlor** [comment]
No idea.  The travis logs indicate that the coveralls upload script did run - I'll start looking for a problem there.

**Comment by vladimir-ch** [comment]
The badge does not show either. It is not related to the build, but it shows that something might have changed on their side. The current markdown in README is:
```markdown
[![Coverage Status](https://img.shields.io/coveralls/gonum/matrix.svg)](https://coveralls.io/r/gonum/matrix)
```
while Coveralls says to use:
```markdown
[![Coverage Status](https://coveralls.io/repos/gonum/matrix/badge.svg?branch=master&service=github)](https://coveralls.io/github/gonum/matrix?branch=master)
```

**Comment by vladimir-ch** [comment]
I'm looking a bit into this. I find suspicious that the test-coverage.sh script echoes variables at several places, goverall also produces output, but none of those appears in the travis log. By bisecting the build history on travis I found that it happened with #152.

**Comment by vladimir-ch** [comment]
Also, travis says:
```
This job ran on our legacy infrastructure. Please read our docs on how to upgrade
```
and the docs say:
```
Not using sudo? Containers sound cool? Add sudo: false to travis.yml and you’re set.
```
We don't seem to be using sudo, so we could upgrade.

**Comment by vladimir-ch** [comment]
stat package has COVERALLS_TOKEN environment variable set in Settings on Travis and coverage is available. matrix package has not the variable set and coverage is not available. Couldn't that be the reason?

**Comment by kortschak** [comment]
> We don't seem to be using sudo, so we could upgrade.

We do in some repos - anything that has cgo, but if it gets us better architectures and throughput when we are not, then SGTM.

>stat package has COVERALLS_TOKEN environment variable set in Settings on Travis and coverage is available. matrix package has not the variable set and coverage is not available. Couldn't that be the reason?

Yes, that seems likely - after looking around I came to the same conclusion independently.

**Comment by kortschak** [comment]
I'm not sure that is the way to fix it though - I don't know how secure the tokens are when they are set via that method. The guides I read all talk about using the travis encrypt method (e.g. http://docs.travis-ci.com/user/environment-variables/#Encrypting-Variables-Using-a-Public-Key).

**Comment by vladimir-ch** [comment]
I have no idea and no experience with this, it is the first time I even opened the coveralls webpage and looked at the test-coverage script (but it seems to me that it could be rewritten in go).

**Comment by kortschak** [comment]
Likewise, I am muddling along.

**Comment by jonlawlor** [comment]
I guess I missed the coveralls key in the travis environment settings?  I regenerated the coveralls api token and plugged it in and it appears to be working now: https://coveralls.io/jobs/8649566

If you are more comfortable using the command line `travis encrypt` command then by all means use it.  I didn't because it makes CI testing testing a bit of a pain and makes each `.travis.yml` unique.

**Comment by kortschak** [comment]
Thanks for doing that. I figured that was probably the reason - is the API key just for running builds? If that's the case then the exposure doesn't seem like too much of an issue. Any ideas?

**Comment by jonlawlor** [comment]
The coveralls api key is only used for uploading the coverage data to coveralls.io and generating the coverage flair.

I don't think coveralls has access to the github repos (visible through the repo settings -> webhooks and services) so the only thing that can be compromised through the coveralls key is the coveralls flair.

There is a setting we could turn on to include coverage % in pull requests, but I turned it off because it was annoying.  If it is re-enabled then coveralls would require some access to the repos.

**Comment by kortschak** [comment]
Thanks, that certainly seems like a reasonable assessment.
