### ISSUE TITLE
mat64: Reset called on a view should panic or reset the concrete matrix value

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#251]
Currently a call to Reset on a View (or blas64.General-derived Dense from a SetRawMatrix call) allows arbitrary over-writing of data. This should not be possible.

There are two options, both require annotating Dense matrices that are a view of either kind:

1. Panic.
2. Set *m to Dense{}.

**Comment by btracey** [comment]
Probably panic? At the moment I can't think of a good reason why you would call Reset on a matrix you didn't allocate.

**Comment by kortschak** [comment]
In that case, all temporary workspaces should also be marked as a view.

**Comment by btracey** [comment]
Sorry, by "allocate" I guess I meant "construct". In more detail, I mean that if I am writing a function that accepts a matrix as input, I do not know if it is a view or not, but I would not want to call Reset on it either, so if I call reset on the matrix, it's probably a bug. I may want to reset matrices I constructed (to save memory/allocations), but in that case I know if the matrix is a view or not and so the panic is avoidable. In this sense, temporary workspaces are more like the latter case since we know their size and know if they are a view.

**Comment by kortschak** [comment]
Yeah, I understood that and I agree. The same can be said of workspaces, we can view on them, but a reset is not OK.

**Comment by kortschak** [comment]
I've had second thoughts about this. This is special-casing something that we should be dealing with via overlap detection. The general case of making it impossible to do bad things to shared data is not something that I now think is reasonable to expect us to do.
