### ISSUE TITLE
use does not correctly return zeroed data slices

### ISSUE THREAD

**Issue by kortschak** [gonum/matrix#64]
The use helper tries to return an adequately sized data slice if one is available from the given []float64. It does not zero those elements on the basis that they will be overwritten before being read. This assumption is not valid for some calls to BLAS routines, e.g. Dgemm calls will add to the values in the recipient. This was identified in #63, but probably impacts other places (Mul and the new MulTrans e.g.).

Probably the best approach is to zero prior to these BLAS calls.

Note that it's probably worthwhile figuring out why the cblas implementation does not fail due to this.

**Comment by kortschak** [comment]
So it seems the beta of 0.0 in cblas gives 0.0 while in goblas (correctly according to IEEE-754) it gives NaN. What do we want to do here?

**Comment by btracey** [comment]
It seems like the reasonable thing is to do what the function says it
does.  We should vet goblas though,  as I had not considered this case

**Comment by kortschak** [comment]
>do what the function says it does

But what is this? IEEE-754 or intuitive. I think IEEE-754, but that makes it at odds with the cblas implementation.

**Comment by jonlawlor** [comment]
This is actually quite disconcerting.  Is it the same with all blas implementations?  I've only tested it on Accelerate.  If it is consistent in the cblas implementations, then we should probably adopt their convention, even if it seems wrong, to keep things consistent.

**Comment by kortschak** [comment]
I'd like to understand more fully before we make a decision, though that does not block this PR.

**Comment by btracey** [comment]
The intuitive behavior (existing implementations aside) is to follow IEEE-754. 

If cblas behavior a mistake, it's easy to see how it's made. Assignment is more efficient that multiplication, so just set it to zero rather than multiply by zero. This is present in the reference implementation. If it's a feature, then I could plausibly see it as a zeroing mechanism (having beta be zero is like the matrix doesn't exist). I guess that's fine, but it's unclear what the consequences are for the rest of the functions. Why would that be the case for beta and not alpha (which does preserve NaN). What about a function like Dtrmm where there is one constant that multiplies matrices on both sides? Does that act like a zero-ing zero or like a floating point zero? The consequences for following IEEE are much clearer, though I agree some broader discussion is needed before we decide what is best.

**Comment by kortschak** [comment]
After discussion with mtj and gri the decision seems to be to have a quiet NaN, i.e. following the blas behaviour.

**Comment by kortschak** [comment]
This was fixed in blas and with 9f4a22dc here.
